"""build_docs.py - writes the pages of every sample, the gallery and the index by technique.

    python tools/build_docs.py            # write the pages
    python tools/build_docs.py --check    # fail (exit 1) when a page is stale or a card disagrees with its code

For each samples/<id>/, from sample.yml and flow/:
  README.md  the overview, for a consultant who decides in a minute: problem, solution, contract, how it works,
             design choices, performance, limits, files, tested versions
  SETUP.md   the step-by-step setup: files, subflows, variables, paste, run, adapt, troubleshooting
At the root: README.md (the gallery, categories in categories.yml), TECHNIQUES.md (samples by technique, vocabulary
in techniques.yml) and samples.json (the catalogue as data).

What is read from the code, never typed by hand:
  subflows and their scope (file name N-Name.txt, header '# local subflow:'), the contract (inputs / outputs),
  flow input / output variables (in_glob_ / out_glob_), UI elements (the ControlRepository block), line counts,
  the CALL line of the example, the settings (SET lines of the first region), the regions (diagram and steps).
"""
import json
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
REPO_URL = "https://github.com/anne-automates/pad-samples"
SEMVER = re.compile(r"\d+\.\d+\.\d+")
TYPES = {"txt": "Text", "num": "Number", "bool": "Boolean", "date": "Datetime", "lst": "List", "tbl": "Datatable",
         "row": "Datarow", "file": "File", "fold": "Folder", "inst": "Instance", "ui": "UI element", "xml": "XML node",
         "cred": "Credential", "obj": "Custom object", "bin": "Binary data", "any": "General value"}
KIND = {"component": "Reusable component", "flow": "End-to-end flow"}
GENERATED = "<!-- Generated by tools/build_docs.py from sample.yml and flow/. Edit those, not this file. -->"
# lines of a flow that talk about how the flow was produced, not about what it does: a reader cannot use them
BUILD_TALK = re.compile(r"tools\\|\.robin\b|build-flow", re.I)


# ---------- reading the Robin ----------

class Subflow:
    def __init__(self, path: Path):
        self.path = path
        self.file = path.name
        m = re.match(r"(\d+)-(.+)\.txt$", path.name)
        if not m:
            raise SystemExit(f"{path}: flow files are named <order>-<SubflowName>.txt")
        self.order, self.name = int(m.group(1)), m.group(2)
        text = path.read_text(encoding="utf-8")
        code, _, repo = text.partition("# [ControlRepository]")
        self.code = code
        head = code.splitlines()[:12]
        self.local = any(l.startswith("# local subflow:") for l in head)
        self.inputs = self._contract(head, "# inputs:")
        self.outputs = self._contract(head, "# outputs:")
        self.lines = self._canvas_lines(code)
        self.ui_elements = self._ui_elements(repo)
        self.regions = [(t, c) for c, t in re.findall(r"^@@regionColor: '(#[0-9A-Fa-f]{6})'\s*\n\*\*REGION (.+)$", code, re.M)]
        self.globals = sorted(set(re.findall(r"\b((?:in|out)_glob_[a-z]+_\w+)", code)))
        self.calls = sorted(set(re.findall(r"^\s*CALL (\w+)", code, re.M)))
        self.call_lines = [l.strip() for l in code.splitlines() if l.strip().startswith("CALL ")]
        self.settings = self._settings(code)
        self.build_talk = [i for i, l in enumerate(text.splitlines(), 1) if BUILD_TALK.search(l)]

    @staticmethod
    def _canvas_lines(code):
        """One canvas line per action: a text literal ($'''...''') may span several lines of the file."""
        lines, inside = [], False
        for l in code.splitlines():
            if not inside and l.strip() and not l.startswith("@@"):
                lines.append(l)
            if l.count("'''") % 2:
                inside = not inside
        return lines

    @staticmethod
    def _contract(head, tag):
        for l in head:
            if l.startswith(tag):
                return [v.strip() for v in l[len(tag):].split(",") if v.strip()]
        return []

    @staticmethod
    def _ui_elements(repo):
        if not repo.strip():
            return []
        data = json.loads(repo[repo.index("{"):])
        names = []
        for sym in data.get("ControlRepositorySymbols", []):
            for screen in json.loads(sym["Repository"]).get("Screens", []):
                names.append((screen.get("Name", ""), [c["Name"] for c in screen.get("Controls", [])]))
        return names

    @staticmethod
    def _settings(code):
        """The SET lines of the first region: the values a user adapts, each with the comment written above it
        (a comment describes the SET lines that follow it, up to the next comment)."""
        m = re.search(r"^\*\*REGION .+?$(.*?)^\*\*ENDREGION", code, re.M | re.S)
        if not m:
            return []
        out, comment = [], ""
        for line in m.group(1).splitlines():
            if line.startswith("# "):
                comment = line[2:].strip()
                continue
            s = re.match(r"^SET (\w+) TO (.+)$", line)
            if not s:
                continue
            v = s.group(2).strip()
            if v.startswith("$'''") and v.endswith("'''"):
                v = v[4:-3].replace("\\\\", "\\").replace("\\'", "'").replace("\\%", "%")
            out.append((s.group(1), v, comment))
        return out

    @property
    def scope(self):
        if self.name == "Main":
            return "Main"
        return "Local" if self.local else "Global"


def type_of(var):
    part = var.split("_")[2] if var.startswith(("in_", "out_")) else var.split("_")[0]
    return TYPES.get(part, "?")


def region_step(title):
    """'3. Convert: Excel publishes...' -> '**Convert**: Excel publishes...'"""
    t = re.sub(r"^\d+\.\s*", "", title)
    head, sep, rest = t.partition(":")
    return f"**{head.strip()}**{sep}{rest}" if sep else f"**{t}**"


# ---------- small writers ----------

def fig(p, width=None):
    w = f' width="{width}"' if width else ""
    return f'<img src="{p["file"]}" alt="{p["caption"]}"{w}><br><sub>{p["caption"]}</sub>'


def mermaid(subs, optional):
    """One row per subflow: its regions in their canvas colours, left to right; one arrow per CALL."""
    shown = [s for s in subs if s.file not in optional]
    out = ["```mermaid", "flowchart TB"]
    for s in shown:
        scope = {"Local": "local function", "Main": "main", "Global": "global"}[s.scope]
        out.append(f'  subgraph {s.name}["<b>{s.name}</b> · {scope}"]')
        out.append("    direction LR")
        for i, (r, color) in enumerate(s.regions, 1):
            title = re.sub(r"^\d+\.\s*", "", r).split(":")[0].replace('"', "'")
            out.append(f'    {s.name}_{i}["{i}. {title}"]')
            out.append(f"    style {s.name}_{i} fill:{color},stroke:#57606a,color:#1f2328")
            if i > 1:
                out.append(f"    {s.name}_{i-1} --> {s.name}_{i}")
        out.append("  end")
    for s in shown:
        for c in s.calls:
            target = next((t for t in subs if t.name == c), None)
            label = f"{len(target.inputs)} in · {len(target.outputs)} out" if target else "calls"
            # subgraph to subgraph: a link that touches a node inside would make mermaid ignore 'direction LR'
            out.append(f'  {s.name} == "CALL · {label}" ==> {c}')
    out.append("```")
    return "\n".join(out)


def contract_table(rows, described):
    """rows: (direction, name). One table per direction, the name first: it is what the reader types."""
    md = []
    for direction in ("Input", "Output"):
        names = [v for d, v in rows if d == direction]
        if not names:
            continue
        md += [f"| {direction}s | Type | Description | Example |", "|---|---|---|---|"]
        for v in names:
            info = described.get(v, {})
            md.append(f"| `{v}` | {type_of(v)} | {info.get('holds', '')} | `{info.get('e.g', '')}` |")
        md.append("")
    return md


# ---------- one sample ----------

class Sample:
    def __init__(self, folder: Path, card: dict, techniques: dict):
        self.folder, self.card, self.techniques = folder, card, techniques
        self.subs = sorted((Subflow(p) for p in (folder / "flow").glob("*.txt")), key=lambda s: s.order)
        cs = card.get("subflows", {})
        self.card_subs = cs
        self.optional = {f for f, v in cs.items() if isinstance(v, dict) and v.get("optional")}
        q = card.get("quick_try") or {}
        self.quick = next((s for s in self.subs if s.file == q.get("file")), None)
        # the full path builds everything but the quick try, which is pasted into Main on its own
        self.full = [s for s in self.subs if s is not self.quick]
        self.to_create = [s for s in self.full if s.name != "Main"]
        self.required = [s for s in self.to_create if s.file not in self.optional]
        self.contract = [(s, "Input", v) for s in self.subs for v in s.inputs] + \
                        [(s, "Output", v) for s in self.subs for v in s.outputs]
        self.glob_vars = sorted({v for s in self.full for v in s.globals})
        self.described = card.get("variables", {})
        self.ui = [(scr, n) for s in self.subs for scr, names in s.ui_elements for n in names]
        self.manual = card.get("manual_steps", [])
        self.pics = card.get("pictures", {})
        self.main = next(s for s in self.subs if s.name == "Main")
        self.functions = [s for s in self.subs if s.local]
        self.version = str(card.get("version", ""))
        self.zip = f"{card['id']}-v{self.version}"
        self.n_in = sum(1 for c in self.contract if c[1] == "Input") + sum(1 for v in self.glob_vars if v.startswith("in_"))
        self.n_out = sum(1 for c in self.contract if c[1] == "Output") + sum(1 for v in self.glob_vars if v.startswith("out_"))
        self.n_vars = self.n_in + self.n_out

    # --- the checks: a card that disagrees with its code never produces a page ---
    def errors(self):
        c, err = self.card, []
        for key in ("id", "version", "title", "summary", "category", "kind", "level", "minutes", "problem", "solution",
                    "techniques", "pictures", "flow_name", "subflows", "run", "tested"):
            if key not in c:
                err.append(f"{key}: required (see templates/sample/sample.yml)")
        if err:
            return err
        if c["id"] != self.folder.name:
            err.append(f"id: {c['id']} must be the folder name {self.folder.name}")
        if not SEMVER.fullmatch(self.version):
            err.append("version: x.y.z is required (1.0.0 for a new sample), see CONTRIBUTING, section Versions")
        changelog = self.folder / "CHANGELOG.md"
        if not changelog.exists() or f"## {self.version}" not in changelog.read_text(encoding="utf-8"):
            err.append(f"CHANGELOG.md: a section '## {self.version} - <date>' is required")
        if c["kind"] not in KIND:
            err.append(f"kind: {c['kind']} must be one of {sorted(KIND)}")
        for t in c["techniques"]:
            if t not in self.techniques:
                err.append(f"techniques: '{t}' is not in techniques.yml (add it there with a title and a summary)")
        if "result" not in self.pics:
            err.append("pictures: result is required")
        # the lowest step of the ladder: a component always offers one block that asks nothing
        q = c.get("quick_try")
        if c["kind"] == "component" and not q:
            err.append("quick_try: a component offers one block to paste into Main that asks nothing (no subflow, no input or output)")
        if q:
            if not self.quick:
                err.append(f"quick_try: flow/{q.get('file')} does not exist")
            elif self.quick.inputs or self.quick.outputs or self.quick.globals or self.quick.calls or self.quick.local:
                err.append(f"quick_try: flow/{q['file']} must ask nothing (no input or output variable, no CALL, not local)")
            for key in ("says", "expect"):
                if key not in q:
                    err.append(f"quick_try: {key} is required")
        for s in self.subs:
            if s.file not in self.card_subs:
                err.append(f"flow/{s.file} is not described under subflows:")
        for f, v in self.card_subs.items():
            if not (self.folder / "flow" / f).exists():
                err.append(f"subflows: {f} has no file in flow/")
            if not isinstance(v, dict) or set(v) - {"does", "optional"} or not v.get("does"):
                err.append(f"subflows: {f} must be {{does: \"...\"}} (quote a text that holds a comma)")
        for v, info in self.described.items():
            if not isinstance(info, dict) or set(info) - {"holds", "e.g", "default"}:
                err.append(f"variables: {v} has unknown keys (quote a text that holds a comma)")
        for s, _, v in self.contract:
            if v not in self.described:
                err.append(f"variables: {v} (contract of {s.name}) has no description")
        for v in self.glob_vars:
            if v not in self.described or "default" not in self.described[v]:
                err.append(f"variables: {v} (flow input/output) needs holds, e.g and default")
        for alt in c.get("design", {}).get("alternatives", []):
            if set(alt) - {"approach", "time", "result", "verdict"}:
                err.append(f"design.alternatives: unknown keys in {alt} (quote a text that holds a comma)")
        return err

    def warnings(self):
        return [f"flow/{s.file}: lines {s.build_talk} talk about how the flow was built (tools, .robin files); "
                "keep only what a reader of the flow needs" for s in self.subs if s.build_talk]

    def requires(self, apps=None):
        apps = list(self.card.get("apps") or []) if apps is None else list(apps)
        lab = self.card.get("lab")
        return ", ".join(apps + ([lab["name"] + " (practice app, included)"] if lab else [])) or "PAD only"

    def meta_line(self):
        c = self.card
        return (f"**{KIND[c['kind']]}** · {c['level'].capitalize()} · Requires {self.requires()} · "
                f"Tested on PAD {c['tested'][-1]['pad']} · v{self.version}")

    def links_line(self):
        return (f"[**Step-by-step setup**](SETUP.md) · "
                f"[Download the sample (zip)]({REPO_URL}/releases/download/{self.zip}/{self.zip}.zip) · "
                f"[Changelog](CHANGELOG.md)")

    def technique_links(self, prefix):
        return " · ".join(f"[{self.techniques[t]['title']}]({prefix}TECHNIQUES.md#{t})" for t in self.card["techniques"])

    # --- the ladder: every way to try the sample, from the one that asks the least to the one that asks the most ---
    def ladder(self):
        c, lab = self.card, self.card.get("lab")
        paths = []
        q = c.get("quick_try")
        if q:
            asks = [f"install {lab['name']}"] if lab else []
            paths.append({"id": "quick", "title": "Quick try", "what": q["says"], "asks": asks,
                          "needs": self.requires(q.get("apps")), "minutes": q.get("minutes", 2)})
        asks = [f"install {lab['name']}"] if lab else []
        if self.required:
            n_local = sum(1 for s in self.required if s.local)
            n_glob = len(self.required) - n_local
            parts = ([f"{n_local} local subflow{'s' if n_local > 1 else ''}"] if n_local else []) + \
                    ([f"{n_glob} subflow{'s' if n_glob > 1 else ''}"] if n_glob else [])
            asks.append(" and ".join(parts))
        if self.n_vars:
            asks.append(f"{self.n_in} input{'s' if self.n_in != 1 else ''}, {self.n_out} output{'s' if self.n_out != 1 else ''}")
        if self.manual:
            asks.append(f"{len(self.manual)} step{'s' if len(self.manual) > 1 else ''} after the paste")
        if self.functions:
            title, what = "Reusable version", "The function and its example call, in a flow of their own."
        elif q:
            title, what = "Full flow", "The complete flow, every subflow in place."
        else:
            title, what = ("Paste and run", "One block into Main.") if not asks else ("Full flow", "The complete flow.")
        paths.append({"id": "full", "title": title, "what": what, "asks": asks, "needs": self.requires(), "minutes": c["minutes"]})
        if self.functions:
            f = self.functions[0]
            paths.append({"id": "own", "title": "In your own flow", "what": f"Call `{f.name}` from the flow you are building.",
                          "asks": [f"the subflow, its {len(f.inputs) + len(f.outputs)} variables and one CALL line"],
                          "needs": "Your flow", "minutes": None})
        # the paths that stand alone, lightest first; reusing the part in your own flow builds on them, so it comes last
        own = [p for p in paths if p["id"] == "own"]
        paths = sorted((p for p in paths if p["id"] != "own"), key=lambda p: (len(p["asks"]), p["minutes"])) + own
        for i, p in enumerate(paths, 1):
            p["n"] = i
            p["anchor"] = f"{i}-" + re.sub(r"[^a-z0-9]+", "-", p["title"].lower()).strip("-")
        return paths

    def ladder_table(self, setup_prefix):
        md = ["| Path | You create | Needs | Time |", "|---|---|---|---|"]
        for p in self.ladder():
            link = "#use-it-in-your-flow" if p["id"] == "own" and setup_prefix else f"{setup_prefix}#{p['anchor']}"
            asks = ", ".join(p["asks"]) if p["asks"] else "Nothing"
            asks = asks[0].upper() + asks[1:]
            time = f"{p['minutes']} min" if p["minutes"] is not None else "Depends on your flow"
            md.append(f"| **[{p['n']}. {p['title']}]({link})**<br>{p['what']} | {asks} | {p['needs']} | {time} |")
        return md + [""]

    # --- README.md: the overview ---
    def overview(self):
        c, pics = self.card, self.pics
        md = [GENERATED, "", f"[All samples](../../README.md) › {c['category']}", "", f"# {c['title']}", "",
              c["summary"], "", self.meta_line(), "", self.links_line(), "", '*For e-learning purposes only: try it in a test environment with the sample data, and review it before any real use. [Disclaimer](../../START-HERE.md#disclaimer)*', "", fig(pics["result"], 720), ""]

        md += ["## Try it", "", "From the path that asks the least to the one that asks the most. Stop at the one you need.", ""]
        md += self.ladder_table("SETUP.md")

        md += ["## Problem", "", c["problem"].strip(), ""]

        md += ["## Solution", "", c["solution"].strip(), ""]
        if c.get("keeps"):
            md += [f"**Kept:** {c['keeps']}", ""]
        md += [f"**Techniques:** {self.technique_links('../../')}", ""]

        md += ["## Use it in your flow", ""]
        if self.functions:
            full = next(p for p in self.ladder() if p["id"] == "full")
            for f in self.functions:
                call = next((l for s in self.subs for l in s.call_lines if l.startswith(f"CALL {f.name} ")), None)
                md += [f"1. Create the local subflow `{f.name}` and its {len(f.inputs)} inputs and {len(f.outputs)} outputs "
                       f"([how](SETUP.md#{full['anchor']})).",
                       f"2. Paste [`flow/{f.file}`](flow/{f.file}) into it ({len(f.lines)} lines).",
                       "3. Call it. The example in `Main`:", ""]
                if call:
                    md += ["```text", call, "```", ""]
                md += contract_table([(d, v) for (s, d, v) in self.contract if s is f], self.described)
                if "errors-as-outputs" in c["techniques"]:
                    md += ["> [!TIP]", f"> `{f.name}` never stops the flow. Test `{next((o for o in f.outputs if o.startswith('out_loc_bool_')), 'the flag')}` "
                           f"after the call and read `{next((o for o in f.outputs if 'Error' in o), 'the error output')}` when it is False.", ""]
        if self.glob_vars:
            md += ["Inputs and outputs of the flow:", ""]
            md += contract_table([("Input" if v.startswith("in_") else "Output", v) for v in self.glob_vars], self.described)
        if self.main.settings and not self.functions:
            md += settings_table(self.main)
        if self.ui:
            md += [f"The {len(self.ui)} UI elements travel inside the pasted code: nothing to capture.", ""]

        md += ["## How it works", "", mermaid(self.full, self.optional), ""]
        core = self.functions[0] if self.functions else self.main
        md += [f"`{core.name}`, region by region:", ""]
        md += [f"{i}. {region_step(r)}" for i, (r, _) in enumerate(core.regions, 1)]
        md.append("")

        design = c.get("design")
        if design:
            md += ["## Design choices", "", f"Measured {design['measured']}.", "",
                   "| Approach | Time | Result | Verdict |", "|---|---|---|---|"]
            md += [f"| {a['approach']} | {a['time']} | {a['result']} | {a['verdict']} |" for a in design["alternatives"]]
            md.append("")
        if c.get("performance"):
            md += ["## Performance", ""] + [f"- {p}" for p in c["performance"]] + [""]
        if c.get("limits"):
            md += ["## Limits", ""] + [f"- {l}" for l in c["limits"]] + [""]

        md += ["## Files", "", "| Subflow | Scope | Lines | Role |", "|---|---|---|---|"]
        for s in self.subs:
            opt = " *(optional)*" if s.file in self.optional else ""
            md.append(f"| [`{s.name}`](flow/{s.file}) | {s.scope} | {len(s.lines)} | {self.card_subs[s.file]['does']}{opt} |")
        md.append("")
        for d, role in (("input", "Sample files"), ("expected", "Output of the test run")):
            if (self.folder / d).exists():
                names = sorted((p.name for p in (self.folder / d).iterdir() if p.is_file()), key=str.lower)
                md.append(f"- {role}, in [`{d}/`]({d}/): {', '.join(f'`{n}`' for n in names)}")
        md.append("")

        md += ["## Tested on", "", "| PAD version | Date | Path | Result |", "|---|---|---|---|"]
        md += [f"| {t['pad']} | {t['date']} | {t.get('path', 'Full flow')} | {'Pass' if t['result'] == 'pass' else 'Fail: ' + t['result']} |"
               for t in c["tested"]]
        md += ["", f"Authors: {', '.join(c.get('authors', []))} · [Changelog](CHANGELOG.md) · "
               f"[Report a problem]({REPO_URL}/issues/new?template=sample-does-not-work.yml&title=%5B{c['id']}%5D+)", ""]
        return "\n".join(md)

    # --- SETUP.md: the paths of the ladder, in its order ---
    def setup(self):
        c, pics = self.card, self.pics
        ladder = self.ladder()
        md = [GENERATED, "", f"[All samples](../../README.md) › [{c['title']}](README.md) › Setup", "",
              f"# Set up: {c['title']}", "", f"Tested on PAD {c['tested'][-1]['pad']} · v{self.version}", "", '*For e-learning purposes only: try it in a test environment with the sample data, and review it before any real use. [Disclaimer](../../START-HERE.md#disclaimer)*', ""]
        if len(ladder) > 1:
            md += ["From the path that asks the least to the one that asks the most. Stop at the one you need.", ""]
        md += self.ladder_table("")

        for p in ladder:
            md += [f"## {p['n']}. {p['title']}", ""]
            sub = 0

            def h(title):
                nonlocal sub
                sub += 1
                md.extend([f"### {p['n']}.{sub} {title}", ""])

            if p["id"] == "quick":
                q, s = c["quick_try"], self.quick
                md += [f"{q['says']} Needs {p['needs']}.", ""]
                h("Prepare the files")
                md += self.files_lines()
                h("Paste the block into Main")
                md += [f"**+ New flow**, any name, **Create**. Click the empty canvas of `Main`, **Ctrl+V** the block of "
                       f"[`flow/{s.file}`](flow/{s.file}). Check: {len(s.lines)} lines, Errors pane empty.", ""]
                md += code_block(s)
                h("Run and check")
                md += ["**Run**. Expected:", ""] + [f"- {e}" for e in q["expect"]] + [""]
                if "picture" in q:
                    md += [fig(q["picture"], 480), ""]
                if s.settings:
                    md += settings_table(s)
                if q.get("option"):
                    md += ["> [!NOTE]", f"> {q['option']}", ""]

            elif p["id"] == "full":
                quick_first = ladder[0]["id"] == "quick"
                h("Prepare the files")
                if lab := c.get("lab"):
                    md += [f"Install the practice app **{lab['name']}**. {lab['why']}", "", "```powershell", lab["install"], "```", ""]
                md += (["The same files as in 1.1.", ""] if quick_first else self.files_lines())
                h("Create the flow" + (" and its subflows" if self.to_create else ""))
                md.append(f"**+ New flow**, name `{c['flow_name']}`, **Create**." + (" Nothing else to create." if not self.to_create else ""))
                if self.to_create:
                    md += [" Then for each subflow: **Subflows** above the canvas › **New**, name, scope, **Save**.", "",
                           "| Subflow name | Scope | Role |", "|---|---|---|"]
                    for s in self.to_create:
                        opt = " *(optional)*" if s.file in self.optional else ""
                        md.append(f"| `{s.name}` | {s.scope} | {self.card_subs[s.file]['does']}{opt} |")
                    if self.functions:
                        md += ["", "> [!WARNING]", "> The scope **Local** is easily lost while you type the name. Check it just before **Save**."]
                    md += ["", "Pictures: [Create a subflow](../../docs/create-a-subflow.md)."]
                md.append("")
                if self.contract or self.glob_vars:
                    h("Create the input and output variables")
                    md += ["They must exist before the paste: the code uses them. Type the names exactly.", ""]
                    for s in self.full:
                        rows = [(d, v) for (t, d, v) in self.contract if t is s]
                        if rows:
                            md += [f"In `{s.name}`: **Variables** › **Local** › **+** › **Input** or **Output**, the name only.", "",
                                   "```text"] + [v for _, v in rows] + ["```", ""]
                    if self.glob_vars:
                        md += ["For the flow: **Variables** › **Global** › **+** › **Input** or **Output**, with the default value.", "",
                               "| Name | Type | Default value |", "|---|---|---|"]
                        md += [f"| `{v}` | {type_of(v)} | `{self.described[v].get('default', '')}` |" for v in self.glob_vars]
                        md.append("")
                    if "variables_pane" in pics:
                        md += [fig(pics["variables_pane"], 300), ""]
                    md += ["Descriptions and examples: [the contract](README.md#use-it-in-your-flow). "
                           "Pictures: [Create input and output variables](../../docs/create-variables.md).", ""]
                h("Paste the code")
                md += ["Open the tab of the subflow, click its empty canvas, **Ctrl+V**.", ""]
                for s in self.full:
                    opt = " *(optional)*" if s.file in self.optional else ""
                    n_ui = sum(len(n) for _, n in s.ui_elements)
                    check = f"Check: {len(s.lines)} lines, Errors pane empty" + (f", {n_ui} UI elements" if n_ui else "") + "."
                    md += [f"**`{s.name}`**{opt} ← [`flow/{s.file}`](flow/{s.file}). {check}", ""] + code_block(s)
                    pic = pics.get("canvas", {}).get(s.file)
                    if pic:
                        md += [fig(pic, 640), ""]
                if self.quick:
                    md += [f"Optional: keep the quick try in the same flow, in a global subflow `{self.quick.name}` "
                           f"([`flow/{self.quick.file}`](flow/{self.quick.file})).", ""]
                if self.manual:
                    h("Finish what the paste cannot carry")
                    for m in self.manual:
                        md += [f"**{m['title']}.** {m['why']} {m['how']}", ""]
                        if "picture" in m:
                            md += [fig(m["picture"], m["picture"].get("width", 300)), ""]
                h("Run and check")
                run = c["run"]
                md += [f"Tab `{run['subflow']}`, **Run**. Expected:", ""] + [f"- {e}" for e in run["expect"]] + [""]
                if "show_file" in run:
                    md += ["```text", (self.folder / run["show_file"]).read_text(encoding="utf-8-sig").rstrip(), "```", ""]
                if "picture" in run:
                    md += [fig(run["picture"], 480), ""]
                if self.main.settings:
                    h("Adapt it to your data")
                    md += settings_table(self.main)

            else:  # own flow
                f = self.functions[0]
                full = next(x for x in ladder if x["id"] == "full")
                md += [f"1. In your flow, create the local subflow `{f.name}` and its variables, as in {full['n']}.2 and {full['n']}.3.",
                       f"2. Paste [`flow/{f.file}`](flow/{f.file}) into it.",
                       f"3. Where you need it, add the CALL line and bind each output to a variable of your flow: "
                       f"[the contract](README.md#use-it-in-your-flow).", ""]

        if c.get("troubleshooting"):
            md += ["## Troubleshooting", "", "| Symptom | Fix |", "|---|---|"]
            md += [f"| {t['when']} | {t['do']} |" for t in c["troubleshooting"]]
            md += ["", f"Other cases: [Troubleshooting a paste](../../docs/troubleshooting.md) · "
                   f"[report a problem]({REPO_URL}/issues/new?template=sample-does-not-work.yml&title=%5B{c['id']}%5D+).", ""]
        return "\n".join(md)

    def files_lines(self):
        return [f"- Copy [`{f['put']}`]({f['put'].replace('*', '')}) into `{f['into']}`. {f.get('note', '')}"
                for f in self.card.get("files", [])] + [""]


def code_block(s):
    return [f"<details><summary>The code ({len(s.lines)} lines)</summary>", "",
            "```text", s.path.read_text(encoding="utf-8").rstrip(), "```", "", "</details>", ""]


def settings_table(s):
    """The first region of a subflow: the only values to change, with the comment the code gives them."""
    md = [f"The values to change are in the first region of `{s.name}` (cyan):", "",
          "| Variable | Value in the sample | What it is |", "|---|---|---|"]
    md += [f"| `{n}` | `{v}` | {d} |" if v else f"| `{n}` | *(empty)* | {d} |" for n, v, d in s.settings]
    return md + [""]


# ---------- root pages ----------

def released(sample):
    """The date of the current version, read from its CHANGELOG section '## x.y.z - YYYY-MM-DD'."""
    text = (sample.folder / "CHANGELOG.md").read_text(encoding="utf-8")
    m = re.search(rf"^## {re.escape(sample.version)} - (\d{{4}}-\d{{2}}-\d{{2}})", text, re.M)
    return m.group(1) if m else ""


def anchor(title):
    return re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")


def gallery(samples, techniques, categories):
    by_cat = {}
    for s in samples:
        by_cat.setdefault(s.card["category"], []).append(s)
    cats = [c for c in categories if c in by_cat]          # the order of categories.yml
    used = {t for s in samples for t in s.card["techniques"]}
    n = len(samples)
    md = [GENERATED, "", "# Power Automate Desktop samples", "",
          "**The Power Automate Desktop creations of Anne**, an AI agent specialised in Power Automate Desktop and "
          "Copilot Studio projects. Everything Anne builds is here, in the open: the Robin files of every subflow, the "
          "sample files, the expected result and the test record of each version.", "",
          "Every sample starts with the quickest way to see it work, then states the problem, the design and the "
          "alternatives it beat, the contract of its reusable parts, its limits and the PAD versions it ran on.", "",
          f"**{n} sample{'s' if n != 1 else ''}** · {len(cats)} categor{'ies' if len(cats) != 1 else 'y'} · "
          f"{len(used)} techniques · [Samples by technique](TECHNIQUES.md) · [How the samples are organised](START-HERE.md) · "
          f"[Contribute](CONTRIBUTING.md) · [Submit a challenge](https://github.com/anne-automates/anne-automates.github.io/issues/new?template=submit-a-challenge.yml) · "
          "[Copilot Studio samples](https://anne-automates.github.io/copilot-studio-samples/)", "",
          "> [!IMPORTANT]", "> **For e-learning purposes.** The samples teach; they are not production-ready. Read the [disclaimer](START-HERE.md#disclaimer).", "",
          "> [!TIP]", "> **Have an automation challenge?** [Submit it to Anne](https://github.com/anne-automates/anne-automates.github.io/issues/new?template=submit-a-challenge.yml): the next samples come from your challenges. Private request: [LinkedIn](https://www.linkedin.com/in/franckmongo/).", "",]
    if len(cats) > 1:
        md += ["**Categories:** " + " · ".join(f"[{c}](#{anchor(c)}) ({len(by_cat[c])})" for c in cats), ""]
    if n > 3:
        latest = sorted(samples, key=lambda s: (released(s), s.card["title"]), reverse=True)[:5]
        md += ["## Latest", ""]
        md += [f"- {released(s)} · [{s.card['title']}](samples/{s.folder.name}/README.md) v{s.version}" for s in latest]
        md.append("")
    for cat in cats:
        md += [f"## {cat}", "", categories[cat]["summary"], "",
               "| | Sample | Techniques | Try it | Requires |", "|---|---|---|---|---|"]
        for s in sorted(by_cat[cat], key=lambda x: x.card["title"].lower()):
            c, rel = s.card, f"samples/{s.folder.name}"
            tech = ", ".join(techniques[t].get("label", techniques[t]["title"]) for t in c["techniques"])
            first = s.ladder()[0]
            try_it = f"{first['minutes']} min, " + (", ".join(first["asks"]) if first["asks"] else "nothing to create")
            md.append(f'| <img src="{rel}/{c["pictures"]["result"]["file"]}" width="150"> '
                      f"| **[{c['title']}]({rel}/README.md)**<br>{c['summary']}<br><sub>{KIND[c['kind']]} · {c['level'].capitalize()} · v{s.version}</sub> "
                      f"| {tech} | {try_it} | {s.requires((c.get('quick_try') or {}).get('apps'))} |")
        md.append("")
    md += ["## What every sample gives you", "",
           "| Overview (`README.md`) | Setup (`SETUP.md`) |", "|---|---|",
           "| Try it · Problem · Solution · Use it in your flow · How it works · Design choices · Performance · Limits · Files · Tested on "
           "| The paths from the lightest to the fullest: Quick try · Full or reusable version · In your own flow · Troubleshooting |", "",
           "The whole catalogue is also in [`samples.json`](samples.json), one entry per sample.", "",
           "## License", "", "[MIT](LICENSE): copy, adapt and use the samples in your own flows and your clients' flows.", ""]
    return "\n".join(md)


def catalogue(samples):
    """samples.json: the gallery as data, for search, filters or any other tool."""
    out = []
    for s in sorted(samples, key=lambda x: x.folder.name.lower()):
        c, first = s.card, s.ladder()[0]
        out.append({"id": c["id"], "title": c["title"], "summary": c["summary"], "category": c["category"], "kind": c["kind"],
                    "level": c["level"], "version": s.version, "released": released(s), "techniques": c["techniques"],
                    "requires": c.get("apps") or [], "quick_try_minutes": first["minutes"] if first["id"] == "quick" else None,
                    "setup_minutes": c["minutes"], "subflows": len(s.required), "inputs": s.n_in, "outputs": s.n_out,
                    "ui_elements": len(s.ui), "tested": c["tested"], "page": f"samples/{s.folder.name}/README.md"})
    return json.dumps({"samples": out}, indent=2, ensure_ascii=False, default=str) + "\n"


def techniques_page(samples, techniques):
    md = [GENERATED, "", "[All samples](README.md)", "", "# Samples by technique", "",
          "A technique is one reusable idea you can carry to another flow. Each sample lists the techniques it shows.", ""]
    for tid, t in techniques.items():
        users = [s for s in samples if tid in s.card["techniques"]]
        if not users:
            continue
        md += [f'<a id="{tid}"></a>', "", f"## {t['title']}", "", t["summary"], ""]
        md += [f"- [{s.card['title']}](samples/{s.folder.name}/README.md): {s.card['summary']}" for s in users]
        md.append("")
    return "\n".join(md)


def main():
    check = "--check" in sys.argv
    techniques = yaml.safe_load((ROOT / "techniques.yml").read_text(encoding="utf-8"))
    categories = yaml.safe_load((ROOT / "categories.yml").read_text(encoding="utf-8"))
    samples, failed, pages = [], False, {}
    for card_path in sorted((ROOT / "samples").glob("*/sample.yml"), key=lambda p: p.parent.name.lower()):
        folder = card_path.parent
        s = Sample(folder, yaml.safe_load(card_path.read_text(encoding="utf-8")), techniques)
        errors = s.errors()
        if s.card.get("category") not in categories:
            errors.append(f"category: '{s.card.get('category')}' is not in categories.yml ({', '.join(categories)})")
        for e in errors:
            print(f"FAIL {folder.name}: {e}")
        for w in s.warnings():
            print(f"WARN {folder.name}: {w}")
        if errors:
            failed = True
            continue
        pages[folder / "README.md"] = s.overview()
        pages[folder / "SETUP.md"] = s.setup()
        samples.append(s)
        print(f"ok   {folder.name}: {len(s.required)} subflow(s), {s.n_vars} variables, {len(s.ui)} UI elements")
    pages[ROOT / "README.md"] = gallery(samples, techniques, categories)
    pages[ROOT / "samples.json"] = catalogue(samples)
    pages[ROOT / "TECHNIQUES.md"] = techniques_page(samples, techniques)
    for path, text in pages.items():
        if check:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                print(f"FAIL {path.relative_to(ROOT).as_posix()} is stale, run tools/build_docs.py")
                failed = True
        elif not failed:
            path.write_text(text, encoding="utf-8")
    sys.exit(1 if failed else 0)


if __name__ == "__main__":
    main()
