"""build_docs.py - writes every samples/<id>/README.md and the gallery README.md from sample.yml + the Robin files.

    python tools/build_docs.py            # write the READMEs
    python tools/build_docs.py --check    # fail (exit 1) when a README is stale or a card disagrees with its code

What is read from the code, never typed by hand:
  subflows and their scope (file name N-Name.txt, header '# local subflow:'), the contract (inputs / outputs),
  flow input / output variables (in_glob_ / out_glob_), UI elements (the ControlRepository block), line counts,
  the settings a user changes (SET lines of the first region), the regions (diagram), the variables PAD creates on paste.
"""
import json
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
REPO_URL = "https://github.com/PowerAutomateDesktop-CopilotStudio/pad-samples"
SEMVER = re.compile(r"\d+\.\d+\.\d+")
TYPES = {"txt": "Text", "num": "Number", "bool": "Boolean", "date": "Datetime", "lst": "List", "tbl": "Datatable",
         "row": "Datarow", "file": "File", "fold": "Folder", "inst": "Instance", "ui": "UI element", "xml": "XML node",
         "cred": "Credential", "obj": "Custom object", "bin": "Binary data", "any": "General value"}
LEVEL_COLOR = {"beginner": "2ea44f", "intermediate": "dbab09", "advanced": "d73a49"}
GENERATED = "<!-- Generated by tools/build_docs.py from sample.yml and flow/. Edit those, not this file. -->"


# ---------- reading the Robin ----------

class Subflow:
    def __init__(self, path: Path):
        self.path = path
        self.file = path.name
        m = re.match(r"(\d+)-(.+)\.txt$", path.name)
        if not m:
            raise SystemExit(f"{path}: flow files are named <order>-<SubflowName>.txt")
        self.order, self.name = int(m.group(1)), m.group(2)
        text = path.read_text(encoding="utf-8")
        code, _, repo = text.partition("# [ControlRepository]")
        self.code = code
        head = code.splitlines()[:12]
        self.local = any(l.startswith("# local subflow:") for l in head)
        self.inputs = self._contract(head, "# inputs:")
        self.outputs = self._contract(head, "# outputs:")
        self.lines = self._canvas_lines(code)
        self.ui_elements = self._ui_elements(repo)
        self.regions = [(t, c) for c, t in re.findall(r"^@@regionColor: '(#[0-9A-Fa-f]{6})'\s*\n\*\*REGION (.+)$", code, re.M)]
        self._region_blocks = re.findall(r"^\*\*REGION .+?$(.*?)^\*\*ENDREGION", code, re.M | re.S)
        self.globals = sorted(set(re.findall(r"\b((?:in|out)_glob_[a-z]+_\w+)", code)))
        self.calls = sorted(set(re.findall(r"^\s*CALL (\w+)", code, re.M)))
        self.settings = self._settings(code)
        made = set(re.findall(r"=>\s*(\w+)", code)) | set(re.findall(r"^\s*SET (\w+) TO", code, re.M))
        made |= set(re.findall(r"^\s*LOOP (?:FOREACH )?(\w+) ", code, re.M))
        self.auto_vars = sorted(v for v in made if not v.startswith(("in_", "out_")))

    @staticmethod
    def _canvas_lines(code):
        """One canvas line per action: a text literal ($'''...''') may span several lines of the file."""
        lines, inside = [], False
        for l in code.splitlines():
            if not inside and l.strip() and not l.startswith("@@"):
                lines.append(l)
            if l.count("'''") % 2:
                inside = not inside
        return lines

    @staticmethod
    def _contract(head, tag):
        for l in head:
            if l.startswith(tag):
                return [v.strip() for v in l[len(tag):].split(",") if v.strip()]
        return []

    @staticmethod
    def _ui_elements(repo):
        if not repo.strip():
            return []
        data = json.loads(repo[repo.index("{"):])
        names = []
        for sym in data.get("ControlRepositorySymbols", []):
            for screen in json.loads(sym["Repository"]).get("Screens", []):
                names.append((screen.get("Name", ""), [c["Name"] for c in screen.get("Controls", [])]))
        return names

    @staticmethod
    def _settings(code):
        """The SET lines of the first region: the values a user adapts."""
        m = re.search(r"^\*\*REGION .+?$(.*?)^\*\*ENDREGION", code, re.M | re.S)
        if not m:
            return []
        out = []
        for name, value in re.findall(r"^SET (\w+) TO (.+)$", m.group(1), re.M):
            v = value.strip()
            if v.startswith("$'''") and v.endswith("'''"):
                v = v[4:-3]
            out.append((name, v))
        return out

    def region_code(self, i):
        return self._region_blocks[i - 1] if i <= len(self._region_blocks) else ""

    @property
    def kind(self):
        if self.name == "Main":
            return "Main (already there)"
        return "Local" if self.local else "Global"


def type_of(var):
    part = var.split("_")[2] if var.startswith(("in_", "out_")) else var.split("_")[0]
    return TYPES.get(part, "?")


# ---------- writing the README ----------

def badge(label, message, color):
    enc = lambda s: s.replace("-", "--").replace("_", "__").replace(" ", "%20")
    return f"![{label}: {message}](https://img.shields.io/badge/{enc(label)}-{enc(message)}-{color})"


def fig(p, width=None):
    w = f' width="{width}"' if width else ""
    return f'<img src="{p["file"]}" alt="{p["caption"]}"{w}><br><sub>{p["caption"]}</sub>'


def mermaid(subs, optional):
    """One row per subflow: its regions in their canvas colours, left to right; one arrow per CALL."""
    shown = [s for s in subs if s.file not in optional]
    out = ["```mermaid", "flowchart TB"]
    for s in shown:
        scope = "local function" if s.local else ("main" if s.name == "Main" else "global")
        out.append(f'  subgraph {s.name}["<b>{s.name}</b> · {scope}"]')
        out.append("    direction LR")
        for i, (r, color) in enumerate(s.regions, 1):
            title = re.sub(r"^\d+\.\s*", "", r).split(":")[0].replace('"', "'")
            out.append(f'    {s.name}_{i}["{i}. {title}"]')
            out.append(f"    style {s.name}_{i} fill:{color},stroke:#57606a,color:#1f2328")
            if i > 1:
                out.append(f"    {s.name}_{i-1} --> {s.name}_{i}")
        out.append("  end")
    for s in shown:
        for c in s.calls:
            target = next((t for t in subs if t.name == c), None)
            label = f"{len(target.inputs)} in · {len(target.outputs)} out" if target else "calls"
            # subgraph to subgraph: a link that touches a node inside would make mermaid ignore 'direction LR'
            out.append(f'  {s.name} == "CALL · {label}" ==> {c}')
    out.append("```")
    return "\n".join(out)


def sample_readme(folder: Path, card: dict):
    subs = sorted((Subflow(p) for p in (folder / "flow").glob("*.txt")), key=lambda s: s.order)
    errors = []
    card_subs = card.get("subflows", {})
    for s in subs:
        if s.file not in card_subs:
            errors.append(f"flow/{s.file} is not described under subflows:")
    for f, v in card_subs.items():
        if not (folder / "flow" / f).exists():
            errors.append(f"subflows: {f} has no file in flow/")
        if not isinstance(v, dict) or set(v) - {"does", "optional"} or not v.get("does"):
            errors.append(f"subflows: {f} must be {{does: \"...\"}} (quote a text that holds a comma)")
    for v, info in card.get("variables", {}).items():
        if not isinstance(info, dict) or set(info) - {"holds", "e.g", "default"}:
            errors.append(f"variables: {v} has unknown keys {sorted(info)} (quote a text that holds a comma)")
    optional = {f for f, v in card_subs.items() if isinstance(v, dict) and v.get("optional")}
    to_create = [s for s in subs if s.name != "Main"]
    required = [s for s in to_create if s.file not in optional]
    contract = [(s, "Input", v) for s in subs for v in s.inputs] + [(s, "Output", v) for s in subs for v in s.outputs]
    glob_vars = sorted({v for s in subs for v in s.globals})
    described = card.get("variables", {})
    for s, _, v in contract:
        if v not in described:
            errors.append(f"variables: {v} (contract of {s.name}) has no description")
    for v in glob_vars:
        if v not in described or "default" not in described[v]:
            errors.append(f"variables: {v} (flow input/output) needs holds, e.g and default")
    ui = [(scr, n) for s in subs for scr, names in s.ui_elements for n in names]
    manual = card.get("manual_steps", [])
    pics = card.get("pictures", {})
    main_file = next(s for s in subs if s.name == "Main")
    level = card["level"]
    # versions: one per sample (x.y.z), with its entry in CHANGELOG.md ; the tag <id>-v<version> publishes the zip
    version = str(card.get("version", ""))
    if not SEMVER.fullmatch(version):
        errors.append("version: x.y.z is required (1.0.0 for a new sample), see CONTRIBUTING, section Versions")
    changelog = folder / "CHANGELOG.md"
    if not changelog.exists() or f"## {version}" not in changelog.read_text(encoding="utf-8"):
        errors.append(f"CHANGELOG.md: a section '## {version} - <date>' is required")
    if card.get("id") != folder.name:
        errors.append(f"id: {card.get('id')} must be the folder name {folder.name}")
    zip_name = f"{card['id']}-v{version}"

    md = [GENERATED, "", "[⬅ All samples](../../README.md)", "", f"# {card['title']}", ""]
    md.append(" ".join([
        badge("level", level, LEVEL_COLOR[level]),
        badge("time", f"{card['minutes']} min", "0969da"),
        badge("tested on PAD", card["tested"][-1]["pad"].rsplit(".", 1)[0], "6f42c1"),
        badge("type", card["kind"], "57606a"),
        badge("version", version, "1a7f37"),
    ]))
    md += ["", f"**{card['summary']}**", "",
           f"⬇️ **[Download this sample]({REPO_URL}/releases/download/{zip_name}/{zip_name}.zip)**: the flow, the sample files "
           f"and the expected result in one zip (version {version}, [what changed](CHANGELOG.md)).", ""]
    if "before" in pics:
        md += ["| Before | After |", "|---|---|", f"| {fig(pics['before'])} | {fig(pics['result'])} |", ""]
    elif "result" in pics:
        md += [fig(pics["result"], 560), ""]

    md += ["## The job", "", card["the_job"].strip(), ""]

    # at a glance
    md += ["## What you will create", "", "| | | |", "|---|---|---|"]
    names = ", ".join(f"`{s.name}`" + (" *(optional)*" if s.file in optional else "") for s in to_create)
    md.append(f"| 🧩 | **Subflows to create** | {f'{len(required)}: {names}' if to_create else 'none, everything goes in Main'} |")
    n_in = sum(1 for c in contract if c[1] == "Input") + sum(1 for v in glob_vars if v.startswith("in_"))
    n_out = sum(1 for c in contract if c[1] == "Output") + sum(1 for v in glob_vars if v.startswith("out_"))
    md.append(f"| 📥 | **Input / output variables to create** | {f'{n_in} inputs, {n_out} outputs' if n_in + n_out else 'none'} |")
    auto = sorted({v for s in subs for v in s.auto_vars})
    md.append(f"| ✨ | **Other variables** | {len(auto)}, created by PAD when you paste: nothing to do |")
    md.append(f"| 🖱️ | **UI elements** | {f'{len(ui)}, pasted with the code: nothing to do' if ui else 'none'} |")
    md.append(f"| ✋ | **Manual steps after the paste** | {len(manual) or 'none'} |")
    apps = card.get("apps") or []
    lab = card.get("lab")
    md.append(f"| 💻 | **Apps** | {', '.join(apps + ([lab['name'] + ' (practice app, included)'] if lab else [])) or 'PAD only'} |")
    md.append("")

    md += ["## How it works", "", "Each box is a region of the flow, in the colour you will see on the canvas.", "",
           mermaid(subs, optional), ""]

    step = 0
    if "quick_try" in card:
        q = card["quick_try"]
        md += ["> [!TIP]", f"> **In a hurry? Try it in 2 minutes.** {q['says']}",
               f"> Create a new flow, open [`flow/{q['file']}`](flow/{q['file']}), copy everything (**Copy raw file** button), "
               "click the empty canvas of `Main`, press **Ctrl+V**, run. The steps below build the reusable version.", ""]

    # step: files
    step += 1
    md += [f"## Step {step} · Prepare the files", ""]
    if lab:
        md += [f"**Install the practice app {lab['name']}** ({lab['why'][0].lower() + lab['why'][1:]})", "",
               "```powershell", lab["install"], "```", ""]
    for f in card.get("files", []):
        md.append(f"- Copy [`{f['put']}`]({f['put'].replace('*', '')}) into `{f['into']}`. {f.get('note', '')}")
    md.append("")

    # step: flow + subflows
    step += 1
    md += [f"## Step {step} · Create the flow{' and its subflows' if to_create else ''}", "",
           f"In Power Automate Desktop select **+ New flow**, name it `{card['flow_name']}`, select **Create**."]
    if to_create:
        md += ["Then, for each line below: **Subflows** list above the canvas › **New**, type the name, choose the scope, **Save**.", "",
               "| # | Subflow name (type it exactly) | Scope | What it does |", "|---|---|---|---|"]
        for s in subs:
            opt = " *(optional)*" if card_subs[s.file].get("optional") else ""
            md.append(f"| {s.order} | `{s.name}` | {s.kind} | {card_subs[s.file]['does']}{opt} |")
        if any(s.local for s in subs):
            md += ["", "> [!WARNING]", "> **Local** is easily lost while you type the name: check that the scope still says Local just before **Save**."]
        md += ["", "📖 [How to create a subflow, with pictures](../../docs/create-a-subflow.md)"]
    md.append("")

    # step: variables
    if contract or glob_vars:
        step += 1
        md += [f"## Step {step} · Create the input and output variables", "",
               "The code uses these names, so they must exist **before** the paste. Type each name exactly, capitals included.", ""]
        for s in subs:
            rows = [(d, v) for (t, d, v) in contract if t is s]
            if not rows:
                continue
            md += [f"**In the subflow `{s.name}`** · Variables pane › **Local** › **+** › Input / Output · only the name", "",
                   "| | Name | Type | Holds | Example |", "|---|---|---|---|---|"]
            for d, v in rows:
                info = described.get(v, {})
                md.append(f"| {'📥&nbsp;Input' if d == 'Input' else '📤&nbsp;Output'} | `{v}` | {type_of(v)} | {info.get('holds', '')} | `{info.get('e.g', '')}` |")
            md.append("")
        if glob_vars:
            md += ["**For the whole flow** · Variables pane › **Global** › **+** › Input / Output", "",
                   "| | Name | Type | Default value | Holds |", "|---|---|---|---|---|"]
            for v in glob_vars:
                info = described.get(v, {})
                md.append(f"| {'📥 Input' if v.startswith('in_') else '📤 Output'} | `{v}` | {type_of(v)} | `{info.get('default', '')}` | {info.get('holds', '')} |")
            md.append("")
        if "variables_pane" in pics:
            md += ["Check: your Variables pane looks like this.", "", fig(pics["variables_pane"], 320), ""]
        md += ["📖 [How to create input and output variables, with pictures](../../docs/create-variables.md)", ""]

    # step: paste
    step += 1
    md += [f"## Step {step} · Paste the code", "",
           "For each block: open the tab of the subflow, click once on its empty canvas, press **Ctrl+V**. "
           "Use the copy button at the top right of each block.", ""]
    for s in subs:
        where = f"tab `{s.name}`"
        opt = " (optional)" if card_subs[s.file].get("optional") else ""
        md += [f"### {s.order}. `{s.name}`{opt} → {where}", ""]
        n_ui = sum(len(n) for _, n in s.ui_elements)
        check = f"✅ After the paste: **{len(s.lines)} lines** on the canvas, the Errors pane empty"
        if n_ui:
            check += f", **{n_ui} UI elements** in the UI elements pane"
        md += [check + ".", ""]
        md += [f"<details><summary>Show the code ({len(s.lines)} lines) · or open <a href=\"flow/{s.file}\">flow/{s.file}</a></summary>", "",
               "```text", s.path.read_text(encoding="utf-8").rstrip(), "```", "", "</details>", ""]
        pic = pics.get("canvas", {}).get(s.file)
        if pic:
            md += [fig(pic, 720), ""]
    if ui:
        md += ["> [!NOTE]", f"> The {len(ui)} UI elements travel **inside** the pasted code (the block that starts with "
               "`# [ControlRepository]`). You do not capture anything.", ""]

    # step: manual steps
    if manual:
        step += 1
        md += [f"## Step {step} · {'The step' if len(manual) == 1 else 'The steps'} the paste cannot do", ""]
        for i, m in enumerate(manual, 1):
            md += [f"**{i}. {m['title']}.** {m['why']}", "", f"> {m['how']}", ""]
            if "picture" in m:
                md += [fig(m["picture"], m["picture"].get("width", 320)), ""]

    # step: run
    step += 1
    run = card["run"]
    md += [f"## Step {step} · Run it and check", "", f"Select the `{run['subflow']}` tab, then **Run**. You should get:", ""]
    md += [f"- {e}" for e in run["expect"]]
    md.append("")
    if "show_file" in run:
        md += ["```text", (folder / run["show_file"]).read_text(encoding="utf-8-sig").rstrip(), "```", ""]
    if "picture" in run:
        md += [fig(run["picture"], 480), ""]

    # adapt
    settings = main_file.settings
    if "quick_try" in card:
        settings = settings or next(s for s in subs if s.file == card["quick_try"]["file"]).settings
    if settings:
        md += ["## Make it yours", "", f"Only the first region of `Main` (cyan) holds values. Double-click a line to change it:", "",
               "| Variable | Value in this sample |", "|---|---|"]
        md += [f"| `{n}` | `{v}` |" for n, v in settings]
        md.append("")

    if card.get("troubleshooting"):
        md += ["## If something goes wrong", "", "| You see | Do this |", "|---|---|"]
        md += [f"| {t['when']} | {t['do']} |" for t in card["troubleshooting"]]
        md += ["", "More: [troubleshooting guide](../../docs/troubleshooting.md) · still stuck? "
               f"[open an issue]({REPO_URL}/issues/new?template=sample-does-not-work.yml&title=%5B{card['id']}%5D+)", ""]

    md += ["<details><summary>The variables PAD creates for you when you paste</summary>", "",
           ", ".join(f"`{v}`" for v in auto), "", "You do not create them. They appear in the Variables pane after the paste.",
           "</details>", ""]
    if ui:
        md += ["<details><summary>The UI elements pasted with the code</summary>", ""]
        for scr in dict.fromkeys(s for s, _ in ui):
            md.append(f"- **{scr}**: " + ", ".join(f"`{n}`" for s2, n in ui if s2 == scr))
        md += ["", "</details>", ""]

    md += ["## Tested on", "", "| PAD version | Date | Result |", "|---|---|---|"]
    md += [f"| {t['pad']} | {t['date']} | {'✅ pass' if t['result'] == 'pass' else '❌ ' + t['result']} |" for t in card["tested"]]
    md += ["", "## In this folder", "", "```text"]
    # the same order on Windows and Linux: the CI must rebuild exactly the page written on the author's PC
    for rel in sorted((p.relative_to(folder).as_posix() for p in folder.rglob("*") if p.is_file() and p.name != "README.md"),
                      key=str.lower):
        md.append(rel)
    md += ["```", "", f"Tags: {' '.join('`' + t + '`' for t in card.get('tags', []))} · Authors: {', '.join(card.get('authors', []))}", ""]
    return "\n".join(md), errors, {"subflows": len(required), "vars": n_in + n_out, "ui": len(ui), "manual": len(manual)}


def gallery(entries):
    md = [GENERATED, "", "# Power Automate Desktop samples", "",
          "**Ready-to-paste flows for real office work.** Each sample is a flow that ran on a real PC, with its sample files, "
          "the expected result, and a page that tells you exactly what to create before you paste.", "",
          "| 1. Pick a sample | 2. Create what the card lists | 3. Copy, paste, run |", "|:---:|:---:|:---:|",
          "| 🔎 below, by task | 🧩 subflows · 📥 variables | 📋 one block per subflow |", "",
          "New to PAD? Read [**Start here**](START-HERE.md): your first paste in 3 minutes.", ""]
    by_cat = {}
    for e in entries:
        by_cat.setdefault(e["card"]["category"], []).append(e)
    for cat in sorted(by_cat):
        md += [f"## {cat}", "", "| | Sample | Level | You create |", "|---|---|---|---|"]
        for e in sorted(by_cat[cat], key=lambda x: x["card"]["title"]):
            c, st, rel = e["card"], e["stats"], e["rel"]
            thumb = c["pictures"]["result"]["file"]
            create = []
            create.append(f"{st['subflows']} subflow{'s' if st['subflows'] > 1 else ''}" if st["subflows"] else "paste only")
            if st["vars"]:
                create.append(f"{st['vars']} variables")
            if st["ui"]:
                create.append(f"{st['ui']} UI elements *(included)*")
            if st["manual"]:
                create.append(f"{st['manual']} manual step")
            md.append(f'| <img src="{rel}/{thumb}" width="160"> | **[{c["title"]}]({rel}/README.md)**<br>{c["summary"]} '
                      f"| {c['level']}<br>{c['minutes']} min · v{c.get('version', '?')} | {' · '.join(create)} |")
        md.append("")
    md += ["## How to read a sample", "", "Every sample page has the same order, so you always know where to look:", "",
           "1. **Before / after** pictures and the job it does",
           "2. **What you will create**: the count of subflows, variables, UI elements and manual steps",
           "3. **Step by step**: files → flow and subflows → variables → paste → the steps the paste cannot do → run",
           "4. **Make it yours**: the only lines to change", "5. **If something goes wrong**", "",
           "## Share your flow", "", "Read [CONTRIBUTING](CONTRIBUTING.md): one folder, one `sample.yml`, the tool writes the page for you.", "",
           "## License", "", "[MIT](LICENSE): copy, adapt and use the samples in your own flows, at work included.", ""]
    return "\n".join(md)


def main():
    check = "--check" in sys.argv
    entries, failed = [], False
    for card_path in sorted((ROOT / "samples").glob("*/sample.yml"), key=lambda p: p.parent.name.lower()):
        folder = card_path.parent
        card = yaml.safe_load(card_path.read_text(encoding="utf-8"))
        text, errors, stats = sample_readme(folder, card)
        for e in errors:
            print(f"FAIL {folder.name}: {e}")
            failed = True
        target = folder / "README.md"
        if check:
            if not target.exists() or target.read_text(encoding="utf-8") != text:
                print(f"FAIL {folder.name}: README.md is stale, run tools/build_docs.py")
                failed = True
        else:
            target.write_text(text, encoding="utf-8")
        entries.append({"card": card, "stats": stats, "rel": f"samples/{folder.name}"})
        print(f"ok   {folder.name}: {stats}")
    g = gallery(entries)
    if check:
        if (ROOT / "README.md").read_text(encoding="utf-8") != g:
            print("FAIL README.md (gallery) is stale")
            failed = True
    else:
        (ROOT / "README.md").write_text(g, encoding="utf-8")
    sys.exit(1 if failed else 0)


if __name__ == "__main__":
    main()
